version: '3'

services:
  redis:
      image: "redis:alpine"
  postgres:
    restart: always
    image: postgres:9.6.5
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
  web:
    build: .
    command: bash -c "python3.8 manage.py migrate --noinput && python3.8 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - media:/opt/media/
      - static:/opt/static/
    depends_on:
      - redis
      - postgres
  celery:
    build: .
    command: celery -A aiv_seeker_service worker -l info
    volumes:
      - media:/opt/media/
      - static:/opt/static/
    depends_on:
      - redis
      - postgres
  flower:
    image: mher/flower
    command: ["flower", "--broker=redis://redis:6379", "--port=5555"]
    ports:
      - 5555:5555
    expose:
      - 5555
    depends_on:
      - redis
      - celery

volumes:
  postgres_data: {}
  media: {}
  static: {}