# Generated by Django 3.0.7 on 2020-06-20 06:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('RUNNING', 'RUNNING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], default='SCHEDULED', max_length=20)),
                ('submitted_by', models.CharField(default='guest', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('submitted_time', models.DateTimeField(default=datetime.datetime(2020, 6, 20, 6, 9, 7, 956415))),
            ],
        ),
        migrations.CreateModel(
            name='SequenceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow')),
            ],
        ),
    ]
