# Generated by Django 3.0.7 on 2020-06-21 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='submitted_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 0, 14, 6, 800165)),
        ),
    ]
