# Generated by Django 3.1 on 2020-06-22 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20200621_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='submitted_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 4, 43, 6, 721491)),
        ),
    ]
