# Generated by Django 3.0.7 on 2020-06-22 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20200622_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='task_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='submitted_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 7, 49, 21, 14779)),
        ),
    ]
